### ISSUE TITLE
Validation on htmlbar does not work

### ISSUE THREAD

**Issue by maximdeveloper** [offirgolan/ember-cp-validations#197]
Hi, 
-
My problem is that the validation on the htmlbar `new.hbs` does not work. 
It is so confused for me, because I have a basic Ember project. I went through the [tutorial](https://github.com/offirgolan/ember-cp-validations) on github step by step and it just does not work.

What I've done is that:

- add `Validations` variable to `rental.js` model
- add helper `v-get` to `new.hbs`

I should be grateful if you could help me figure out why it does not work.

[This is](https://github.com/maximdeveloper/study_ember) my project on github.
Version of Ember that I used is  `2.5.0`.

**Comment by blimmer** [comment]
The problem in your example code is that your model hook is returning an array of models.

```javascript
// app/routes/new.js
export default Ember.Route.extend({
  model() {
    return this.store.findAll('rental');
  }
});
```

Therefore, there are no validations on the list of three rentals. Since it's a new rental, you'll probably want to change your model hook to create a new record:
```javascript
export default Ember.Route.extend({
  model() {
    return this.store.createRecord('rental');
  }
});
```

I did this on your project and it worked as I expected. Also, as you get started with Ember, the Ember Community Slack help channel is a great resource!

http://emberjs.com/community/
