### ISSUE TITLE
Need a complimentary library to support form validation

### ISSUE THREAD

**Issue by blimmer** [offirgolan/ember-cp-validations#23]
As others have eluded, we need a solution to provide a better UX for displaying validations when used on a form. We don't think that this should be provided as part of this library, but there's interest in defining/developing a solution that works well with this library.

Before we start designing the solution, we want to explore the problem space with some examples ranging from simple to very complex forms. 

To facilitate this discussion, I've created [this repo](https://github.com/blimmer/ember-form-examples) to show running examples. Please fork and provide PRs with forms you've needed to build in the past that has been a struggle with the solutions available today.

Overall here are the parameters we're considering as part of this project:
- not bound to one design language (e.g. bootstrap, foundation, etc.)
- option to defer displaying validation errors until the user has somehow interacted with the form/field
- disabling the submit button until validation passes

**Comment by offirgolan** [comment]
@blimmer I dont believe this is currently in scope nor will it ever be. There are a good amount of form libraries out there have adopted CP Validations or at least created hooks for this library so it can be used side by side. 

Example addons:

- [ember-bootstrap](https://github.com/kaliber5/ember-bootstrap)
- [ember-cli-materialize](https://github.com/mike-north/ember-cli-materialize)

Im gonna go ahead and close this issue. Feel free to reopen if you feel otherwise.
