### ISSUE TITLE
Deleted records are still validated

### ISSUE THREAD

**Issue by aaronbhansen** [offirgolan/ember-cp-validations#304]
### Environment

Ember Version: 2.6.3
Ember CLI Version: 2.6
Ember CP Validations Version: 2.9.3

### Steps to Reproduce

I was doing some work on our app and was curious if deleted, but not saved records would still validate, and they do. I believe the has-many validator should be updated to ignore deleted but not saved to the server records.

I wrote a test based on my previous ones to show this functionality. 

Also, made me think about the presence validator and belongs-to. If a record is deleted but not saved, and presence: true is there, is that record valid? 

```js
test("order with invalid question shows valid if invalid question is deleted in reverse order", function(assert) {
  assert.expect(8);
  var order = this.subject({ id: 1, source: 'external' });

  var orderLine, orderSelection, orderSelectionQuestion;

  let store = this.store();
  Ember.run(() => {
    let fakeSave = function(model) {
      model.get('_internalModel').adapterWillCommit();
      model.get('_internalModel').adapterDidCommit();
    };

    orderLine = store.createRecord('order-line', { id: 1, order: order, type: "item" });
    orderSelection = store.createRecord('order-selection', { id: 1, order: order, line: orderLine, quantity: 1 });
    orderSelectionQuestion = store.createRecord('order-selection-question', { id: 1, order: order, selection: orderSelection, text: 'answer' });
    orderSelectionQuestion2 = store.createRecord('order-selection-question', { id: 2, order: order, selection: orderSelection });

    fakeSave(order);
    fakeSave(orderLine);
    fakeSave(orderSelection);
    fakeSave(orderSelectionQuestion);
    fakeSave(orderSelectionQuestion2);
  });

  assert.equal(order.get('lines.length'), 1, 'Order has 1 Order Line');
  assert.equal(orderLine.get('selections.length'), 1, 'Order Line has 1 Order Selection');
  assert.equal(orderSelection.get('questions.length'), 2, 'Order Selection has 2 Order Selection Question');

  let done = assert.async();

  orderSelectionQuestion2.validate().then(({ validations }) => {
    assert.equal(validations.get('isValid'), false, 'Order Selection Question 2 should be invalid');
    return orderSelectionQuestion.validate();
  }).then(({ validations }) => {
    assert.equal(validations.get('isValid'), true, 'Order Selection Question should be valid');
    return orderSelection.validate();
  }).then(({ validations }) => {
    assert.equal(validations.get('isValid'), false, 'Order Selection should be invalid because of Order Selection Question 2');
    orderSelectionQuestion2.deleteRecord();
    return orderSelection.validate();
  }).then(({ validations }) => {
    assert.equal(orderSelection.get('questions.length'), 2, 'Order Selection has 2 Order Selection Question');
    assert.equal(validations.get('isValid'), true, 'Order Selection should be valid because invalid Order Selection Question 2 was marked deleted');
    done();
  });
});
```

**Comment by offirgolan** [comment]
@aaronbhansen those are some good points but open up some other questions. 

> I believe the has-many validator should be updated to ignore deleted but not saved to the server records.

This task is rather simple. All that is required is to filter out all records that have `model.get('isDeleted) !== true` but what happens when all records in the has-many array are deleted? Does it return `true` to express a valid state?

The same can be said to the belongs-to validator. If the given record is deleted, does it too return `true` to express a valid state? 

> Also, made me think about the presence validator and belongs-to. If a record is deleted but not saved, and presence: true is there, is that record valid?

This can be said about any validator. Should a validator be able to validate a a deleted record?

Follow up question (just spit ballin here), where should this logic go? If you look at it from a user's perspective, you can simply create a global disabled option

```js
const Validations = buildValidations({...}, {
  disabled: computed.readOnly('model.isDeleted')
});
```

But this can be easily overwritten further down the chain of validations.... 

Another idea is to add an event listener to destroy the validations object when the record gets deleted. The thing is, if a record is marked as deleted it can be easily rolled back... soooo this idea is out as well. 

This leads me to believe that there should be some internal global way to disable all validations on a deleted record. Just gotta figure out where to put it. 

In my opinion, I think that a deleted record should always be in a valid state since the global validation state and upstream validation states should not be affected by it. 

Maybe @blimmer could give me some insight on this as well. 😄

**Comment by aaronbhansen** [comment]
> In my opinion, I think that a deleted record should always be in a valid state since the global validation state and upstream validation states should not be affected by it.

I agree, mostly I wanted to throw this ticket out there and get a discussion started. 

I think any has-many object shouldn't be part of the validation. The reason I brought up presence and not the other was validators is I think most validators should be ignored if the belongs-to object is deleted. But presence is a unique situation, where the relationship still exists (and the object is present), but its not really valid. Anyway, hopefully you can find the right place to add in the validations to ignore deleted records. 

When working with ember data, we do a lot of soft deletes and then save all at once, so it would be great to have a way to ensure those deletes don't effect the overall parent model validations.
