### ISSUE TITLE
Nested objects

### ISSUE THREAD

**Issue by basz** [offirgolan/ember-cp-validations#444]
According to https://github.com/offirgolan/ember-cp-validations/issues/91 model fragments should validated...

However I cannot get this to work while using ember-bootstrap. Only properties defined on the root object are validated. Perhaps it is an integration issue?

**Comment by offirgolan** [comment]
@basz can you please add snippets of your validations + template, as well as the versions originally requested?

**Comment by basz** [comment]
here this shows what i mean: https://github.com/basz/ember-validation-test-app

two models written (to local storage)

thing
part

where `part` is a *fragment* of `thing`.

both part and thing have their own validation definitions

only the root properties (of thing) are validated...

thanks for the effort!

**Comment by offirgolan** [comment]
@basz this is because the validations are integrated only with the form's model and not on the child models. This is an issue that should be solved within ember-bootstrap. Right now, the integration between the two grabs the top level validations object and uses the assigned input's property to detect which attribute to get the validations from. 

In this case, `thing.validations.attrs.part.name` doesnt exist as the validations for `part.name` only exist on `part`. 

What I did in the past is nest child model forms within the parent form and use the relational validators to determine if the form is valid or not. Maybe if you post an issue about this in ember-bootstrap, @simonihmig can address this sort of issue. 

My proposed solution is the ability to override the model that is being validated on the input. I see that as the easiest solution and the current integration addon wouldnt need to be changed. 

```hbs
{{#bs-form model=model}}
  {{bs-input property="foo"}}
  {{bs-input property="foo" model=model.part}}
{{/bs-form}}
```

I forgot the exact API but something like that would be work well. Im not sure if there would be any complications though.

**Comment by simonihmig** [comment]
Thanks for pulling me in. Have not looked at this in detail so far, but will see if we can support that use case of nested models in a more straightforward way, either in ember-bootstrap itself or in ember-bootstrap-cp-validations. 

@basz as suggested could you please open an issue for that on ember-bootstrap. I guess we can than close this one...

**Comment by offirgolan** [comment]
@simonihmig thanks for taking a look into this. Let me know if there is anything I can do to help from my end.
