### ISSUE TITLE
Number validator?

### ISSUE THREAD

**Issue by dzbo** [offirgolan/ember-cp-validations#60]
I can't locate number validator neither in code nor in the docs. I see there is message for that https://github.com/offirgolan/ember-cp-validations/blob/master/addon/validators/messages.js#L78. Should I create custom one then?

**Comment by offirgolan** [comment]
My goal was to be able to replace the number validator with the [inclusion/exclusion validators](http://offirgolan.github.io/ember-cp-validations/docs/validators/inclusion/index.html) since they are type checked. If this isnt enough, just use a custom validator for now. If there is a need for a number validator we can create one later down the line.

**Comment by dzbo** [comment]
Yep, I've created my own number validator for now. But yea, it would be great to have one built in, it's rather common.

**Comment by offirgolan** [comment]
Please upgrade to 2.1.0 and check out the [number validator docs](http://offirgolan.github.io/ember-cp-validations/docs/validators/number/index.html) :smile_cat:
