### ISSUE TITLE
Add Validation to Glimmer component

### ISSUE THREAD

**Issue by mwalper** [offirgolan/ember-cp-validations#652]
I'm curious on how to add validation to a Glimmer Component. Since it is not possible to add mixins and the `@hasvalidation ` decorator is gone.

I try to add form validation to a glimmer component with no model attached.

### Environment

- Ember Version: 3.12
- Ember CLI Version: 3.12
- Ember CP Validations Version: 4.0.0-beta.9

**Comment by trek** [comment]
@mwalper it's a bit clunky, but possible. You can't add validations directly to the Glimmer object because (as far as I can tell) validations rely on setup from within `buildValidations` to be connected properly.

However, if you're willing to delegate the validation behavior to a helper class  _within_ the Glimmer component, you can get most of what you're after while this addon (or some other addon) is updated to avoid using Mixins:

It would look like this in use:

```
import Component from '@glimmer/component';
import EmberObject, { action } from '@ember/object';
import { setOwner } from '@ember/application';

const ValidationsMixin = buildValidations({
  ... your validations here ...
});

const Validations = EmberObject.extend(ValidationsMixin);

export default class SomeComponent extends Component {
  constructor(owner, args) {
    super(...arguments);
    this.validator = Validations.create();
    setOwner(this.validator, owner);
  }
  
  @action async submit(event) {
    event.preventDefault();
    let isValid = await this.validator.get('validations.isValid');
  }
}
```

The main trick to getting this working is providing an `owner` object to the `Validations` helper object. Validations are looked up by name through Ember's injection system, and `owner` is what gives you access to this.

Thankfully the first argument to a Glimmer component is the `owner`

**Comment by mwalper** [comment]
@trek thank you for your response. 
Using the ObjectProxy i get the following error:

`Uncaught TypeError: component.get is not a function`

**Comment by trek** [comment]
@mwalper I'd need to see your app code to know what's happening, but I suspect you're calling `get` on the glimmer component? Glimmer components aren't descendants of `Ember.Object` so don't have `get` as a method.

**Comment by mwalper** [comment]
@trek my mistake. I tried to access the error state on the Glimmer Component using the `v-get` helper. Accessing the error state on the `ObjectProxy` fixed the problem.
Thanks again for your help. Hoping that the dependence on mixins in this great addon will soon be removed.
