### ISSUE TITLE
i18n message example

### ISSUE THREAD

**Issue by jasonmit** [offirgolan/ember-cp-validations#9]
Spoke to @stefanpenner awhile back about this, and sticking to my word to investigate it.

Will poke at it at some point this week to see how we'll be able to leverage the services of ember-intl || ember-i18n to resolve translation keys and handle formatting with params.

**Comment by offirgolan** [comment]
Yeah that was on my todo list as well. I don't think it should be too difficult.... all error messages are stored in `app/validators/messages` so porting that to ember-intl or ember-i18n should be pretty straight forward

**Comment by stefanpenner** [comment]
> Spoke to @stefanpenner awhile back about this, and

:+1:

**Comment by jasonmit** [comment]
@offirgolan I have the sense it will not be that straight forward because both ember intl and i18n require a container lookup and ember intl handles ICU message syntax where your examples use Ember.String.fmt.

**Comment by offirgolan** [comment]
Accessing the messages in the current context is also done via a container lookup. As for the ICU message syntax, that would be something that we would both need to explore.

**Comment by blimmer** [comment]
A few ideas:

* what do we think about implementing this as a validation-messages service? Either way, we'll need to convert the `utils/messages.js` file to be an Ember Object so we can try to inject the i18n/intl service and pull from them if present. this would be nice because the defaults would be cached in the singleton service.

* we'll need to invalidate the messages on locale change

* I'm thinking each flavor of library will need to handle converting to their desired format of string formatting. this library uses String.fmt, i18n uses curlies and intl uses ICU.

What do y'all think?

**Comment by offirgolan** [comment]
> I'm thinking each flavor of library will need to handle converting to their desired format of string formatting. this library uses String.fmt, i18n uses curlies and intl uses ICU.

I think we may need to step away from String.fmt since it seems like it's being deprecated. We can always move over to using curlies or ICU formatted strings and then create two separate files and choose based on which library is being used.
